# Конфигурационный файл для IRC-клиента
# Bot config file, some functions are not implemented yet

[ircServer] # Параметры IRC сервера
ircServerHost = "irc.rizon.net"    # Адрес сервера IRC / IRC server host
ircServerPort = 7000               # Порт сервера IRC / IRC server port
ircServerPass = ""                 # Пароль IRC сервера (ZNC) / IRC server password (for ZNC)

[ircClient] # Параметры IRC клиента
ircBotUser = "pybot"               # Имя пользователя бота / Bot username
ircBotNick = "PythonBot"           # Ник бота / Bot nickname
ircBotRnam = "Python IRC Bot"      # Реально имя (RealName) / Bot realname
ircBotNspw = "YOUR_PASSWORD"       # Пароль NickServ / NickServ password
ircBotChan = "#test"               # Канал, к которому присоединяется бот / Bot initial channel
ircBotAdmi = "BotMaster"           # Ник администратора / Bot admin nick
ircBotAcon = false                 # Флаг автозапуска (true/false) / Autorun falg
ircBotCsym = "."                   # Символ команды бота / Bot command starting symbol
ircBotRcon = ""			   # Команды серверу при соединении / Command to ircd on connect
ircBotDccv = "Python IRC Bot"      # Версия при CTCP запросе / CTCP VERSION reply
